[tool.poetry]
name = "trading-alg"
version = "0.1.0"
description = ""
authors = ["Miguel Tallón Benítez <stallon10@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
